name: Processing Infinity
markdown: redcarpet
highlighter: true
timezone: Europe/Riga
encoding: UTF-8
permalink: /weblog/:year/:month/:day/:title
url: http://www.processinginfinity.com
exclude: [ ProcInf.sublime-* ]